spring.application.name=spring-boot-app
server.port=8080
management.endpoints.web.exposure.include=mappings
spring.data.mongodb.uri=mongodb://admin:password123@localhost:27017/shopping_list?authSource=admin
